[package]
name = "website-stalker"
description = "Track changes on websites via git"
version = "0.11.0"
license = "LGPL-2.1-or-later"
repository = "https://github.com/EdJoPaTo/website-stalker"
authors = ["EdJoPaTo <website-stalker-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# See https://doc.rust-lang.org/rustc/codegen-options/index.html
codegen-units = 1
lto = true

[build-dependencies]
clap = "2"
regex = "1"

[dependencies]
anyhow = "1"
html5ever = "0.25"
itertools = "0.10"
kuchiki = "0.8"
regex = "1"
scraper = "0.12"
serde_yaml = "0.8"
void = "1"

[dependencies.clap]
version = "2"
features = ["wrap_help"]

[dependencies.git2]
version = "0.13"
default-features = false

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "gzip", "brotli"]

[dependencies.rss]
version = "1"
features = ["validation"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.url]
version = "2"
features = ["serde"]

[dev-dependencies]
tempfile = "3"
