[package]
name = "website-stalker"
description = "Track changes on websites via git"
version = "0.1.0"
license = "LGPL-3.0-or-later"
repository = "https://github.com/EdJoPaTo/website-stalker"
authors = ["EdJoPaTo <website-stalker-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
config = "0.11"
serde_yaml = "0.8"
ureq = "2"

[dependencies.clap]
version = "2"
features = ["wrap_help"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.url]
version = "2"
features = ["serde"]
