name: Update Arch Linux User Repository (AUR)

on:
  push:
    tags:
      - 'v*'

jobs:
  aur-publish:
    name: AUR ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - website-stalker
          - website-stalker-bin
    steps:
      - uses: ATiltedTree/create-aur-release@v1
        with:
          package_name: ${{ matrix.name }}
          commit_username: GitHub Actions
          commit_email: website-stalker-github-actions@edjopato.de
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
