name: Test Coverage

on:
  push:
  pull_request:

jobs:
  tarpaulin:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        shell: bash -eux {0}
        run: |
          rustup --version
          rustup show
          rustup toolchain install stable --profile minimal
          rustup default stable

      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          key: tarpaulin-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: tarpaulin-
          path: |
            ~/.cargo/.crates*
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run cargo-tarpaulin
        run: cargo tarpaulin --all-features --out Html

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: tarpaulin-report.html
