name: Test and Build Rust

on:
  push:
  pull_request:

jobs:
  test:
    name: Test ${{ matrix.os }} ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Check the 3 platforms and ensure there is not even a single warning
          - os: ubuntu-latest
            toolchain: stable
            clippyargs: -D clippy::pedantic -D warnings
            experimental: false
          - os: macOS-latest
            toolchain: stable
            clippyargs: -D clippy::pedantic -D warnings
            experimental: false
          - os: windows-latest
            toolchain: stable
            clippyargs: -D clippy::pedantic -D warnings
            experimental: false

          # Check beta/nightly (potentially buggy) and maybe get some glances on soon to be lints
          - os: ubuntu-latest
            toolchain: beta
            clippyargs: -W clippy::pedantic
            experimental: true
          - os: ubuntu-latest
            toolchain: nightly
            clippyargs: -W clippy::pedantic
            experimental: true

          # Check if it is still running on older Rust versions.
          # Sometimes they dont have lint bugfixes which results in false positives -> Dont error, just warn.
          # Also some specified lints are not yet existing in the older rust version -> allow unknown lints.
          # - os: ubuntu-latest
          #   toolchain: 1.41.1 # Debian 10 Buster
          #   clippyargs: -A unknown-lints -A clippy::unknown-clippy-lints
          #   experimental: false
          - os: ubuntu-latest
            toolchain: 1.48.0 # Debian 11 Bullseye
            clippyargs: -A unknown-lints -A clippy::unknown-clippy-lints
            experimental: false
          - os: ubuntu-latest
            toolchain: 1.52.0 # Alpine 3.14
            clippyargs: -A unknown-lints
            experimental: false
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          profile: minimal
          toolchain: ${{ matrix.toolchain }}

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --locked --all-targets --all-features -- ${{ matrix.clippyargs }}

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --locked --all-features

  github-release:
    name: Release ${{ matrix.triple }}
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            triple: arm-unknown-linux-gnueabihf
          - os: ubuntu-latest
            triple: armv7-unknown-linux-gnueabihf
          - os: ubuntu-latest
            triple: aarch64-unknown-linux-gnu

          - os: macOS-latest
            triple: x86_64-apple-darwin
          - os: macOS-latest
            triple: aarch64-apple-darwin

          - os: windows-latest
            triple: x86_64-pc-windows-msvc
          # https://github.com/briansmith/ring/issues/1167
          # - os: windows-latest
          #   triple: aarch64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Artifact Name
        shell: bash
        run: |
          version=$(git describe --tags --match "v*.*.*" --always)
          echo "version is: $version"
          echo "GIT_TAG_VERSION=$version" >> $GITHUB_ENV

          name="website-stalker-$version-${{ matrix.triple }}"
          echo "artifact name is: $name"
          echo "ARTIFACT_NAME=$name" >> $GITHUB_ENV

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: ${{ matrix.triple }}
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        env:
          # TODO: Remove this once it's the default
          SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
        with:
          command: build
          args: --release --verbose --locked --all-features --target ${{ matrix.triple }}
          use-cross: ${{ runner.os == 'Linux' && matrix.triple != 'x86_64-unknown-linux-gnu' }}

      - name: Package (-nix)
        if: runner.os != 'Windows'
        run: >
          tar --gzip -cvf ${{ env.ARTIFACT_NAME }}.tar.gz
          completions LICENSE README.md
          systemd/**/*.service systemd/**/*.timer systemd/**/*.conf
          -C target/${{ matrix.triple }}/release website-stalker
      - name: Package (windows)
        if: runner.os == 'Windows'
        run: |
          7z a ${{ env.ARTIFACT_NAME }}.zip completions LICENSE README.md
          cd target/${{ matrix.triple }}/release
          7z a ../../../${{ env.ARTIFACT_NAME }}.zip website-stalker.exe
          cd -

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.triple }}
          path: |
            *.zip
            *.tar.gz

      - name: GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  aur-publish:
    name: AUR ${{ matrix.name }}
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: github-release
    strategy:
      fail-fast: false
      matrix:
        name:
          - website-stalker
          - website-stalker-bin
    steps:
      - name: Publish AUR package
        uses: ATiltedTree/create-aur-release@v1
        with:
          package_name: ${{ matrix.name }}
          commit_username: GitHub Actions
          commit_email: website-stalker-github-actions@edjopato.de
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
